### ISSUE TITLE
请问这个错误是要安装python2版本才能解决依赖安装问题吗

### ISSUE THREAD

**Issue by zjrwtx** [Mr-Yel/yuque-personal-blog#1]
![image](https://user-images.githubusercontent.com/86822589/213114908-278ee926-ef8e-4453-9c4e-d0f2971c6d21.png)

**Comment by Mr-Yel** [comment]
这个我还没有开发完成，参考了另一个人的uniapp博客，你可以先看一下他的&nbsp;https://juejin.cn/post/7167177950465851406




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月18日(星期三) 下午3:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Mr-Yel/yellll-uniapp] 请问这个错误是要安装python2版本才能解决依赖安装问题吗 (Issue #1)

**Comment by zjrwtx** [comment]
好的 谢谢
